---
title: "Introduction to the charlatan package"
author: "Scott Chamberlain"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: readable
vignette: >
  %\VignetteIndexEntry{Introduction to the charlatan package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
```

`charlatan` xxx

## Install

Development version from Github

```{r eval=FALSE}
devtools::install_github("ropenscilabs/charlatan")
```

```{r}
library("charlatan")
```

## high level function 

... for all fake data operations

```{r}
x <- fraudster()
x$job()
x$name()
x$job()
x$color_name()
```

## locale support

Adding more locales through time, e.g., 

Locale support for job data

```{r}
ch_job(locale = "en_US", n = 3)
ch_job(locale = "fr_FR", n = 3)
ch_job(locale = "hr_HR", n = 3)
ch_job(locale = "uk_UA", n = 3)
ch_job(locale = "zh_TW", n = 3)
```

For colors:

```{r}
ch_color_name(locale = "en_US", n = 3)
ch_color_name(locale = "uk_UA", n = 3)
```

More coming soon ...

## generate a dataset

```{r}
ch_generate()
```

```{r}
ch_generate('job', 'phone_number', n = 30)
```


## person name

```{r}
ch_name()
```

```{r}
ch_name(10)
```


## phone number

```{r}
ch_phone_number()
```

```{r}
ch_phone_number(10)
```

## job

```{r}
ch_job()
```

```{r}
ch_job(10)
```

## credit cards

```{r}
ch_credit_card_provider()
ch_credit_card_provider(n = 4)
```

```{r}
ch_credit_card_number()
ch_credit_card_number(n = 10)
```

```{r}
ch_credit_card_security_code()
ch_credit_card_security_code(10)
```
