# modified from the python library faker:
# https://github.com/joke2k/faker/blob/master/faker/providers/job/fr_CH/__init__.py

job_formats_fr_ch <- c(
  "Accompagnant socioprofessionnel dipl\u00f4m\u00e9",
  "Accompagnateur de randonn\u00e9e avec brevet f\u00e9d\u00e9ral",
  "Accompagnateur social avec brevet f\u00e9d\u00e9ral",
  "Acousticien en syst\u00e8mes auditifs CFC",
  "Administrateur diplom\u00e9 de biens immobiliers",
  "Agent commercial de l\'imprimerie avec brevet f\u00e9d\u00e9ral (BF)",
  "Agent d\'entretien de bateaux",
  "Agent d\'exploitation CFC",
  "Agent de d\u00e9tention avec brevet f\u00e9d\u00e9ral",
  "Agent de maintenance avec brevet f\u00e9d\u00e9ral",
  "Agent de processus avec brevet f\u00e9d\u00e9ral",
  "Agent de propret\u00e9 AFP",
  "Agent de propret\u00e9 CFC",
  "Agent de transport et logistique avec brevet f\u00e9d\u00e9ral",
  "Agent de transports publics CFC",
  "Agent de voyages avec brevet f\u00e9d\u00e9ral",
  "Agent d\u2019entretien de bateaux CFC",
  "Agent d\u2019entretien en assainissement AFP",
  "Agent d\u2019exploitation CFC",
  "Agent en automatique avec brevet f\u00e9d\u00e9ral",
  "Agent en information documentaire CFC",
  "Agent en produits textiles AFP",
  "Agent fiduciaire avec brevet f\u00e9d\u00e9ral",
  "Agent professionnel de protection de personnes et de biens avec brevet f\u00e9d\u00e9ral",
  "Agent professionnel de s\u00e9curit\u00e9 et de surveillance avec brevet f\u00e9d\u00e9ral",
  "Agent relation client CFC",
  "Agent technico-commercial avec brevet f\u00e9d\u00e9ral",
  "Agent technique d\'exploitation avec brevet f\u00e9d\u00e9ral",
  "Agent technique des mati\u00e8res synth\u00e9tiques CFC",
  "Agriculteur CFC (Champ professionnel de l\'agriculture)",
  "agrocommer\u00e7ant dipl\u00f4m\u00e9 ES",
  "Agropraticien AFP",
  "agrotechnicien dipl\u00f4m\u00e9 ES",
  "Aide en informatique AFP",
  "Aide en soins et accompagnement AFP",
  "Aide en technique du b\u00e2timent AFP",
  "Aide-carreleur AFP",
  "Aide-constructeur m\u00e9tallique AFP",
  "Aide-ma\u00e7on AFP",
  "Aide-menuisier AFP",
  "Aide-monteur frigoriste AFP",
  "Aide-mouleur AFP",
  "Aide-peintre AFP",
  "Aide-pl\u00e2trier AFP",
  "Aide-polyb\u00e2tisseur AFP",
  "ambulancier dipl\u00f4m\u00e9 ES",
  "Analyste financier et gestionnaire de fortunes dipl\u00f4m\u00e9",
  "Arboriculteur CFC (Champ professionnel de l\'agriculture)",
  "Armurier",
  "Armurier CFC",
  "Art-th\u00e9rapeute dipl\u00f4m\u00e9 (DF)",
  "Artisan du bois CFC",
  "Artisan du cuir et du textile CFC",
  "Artisan en conservation des monument historiques avec brevet f\u00e9d\u00e9ral",
  "Assistant de bureau AFP",
  "Assistant de direction avec brevet f\u00e9d\u00e9ral",
  "Assistant de gestion en pharmacie avec brevet f\u00e9d\u00e9ral",
  "Assistant dentaire CFC",
  "Assistant du commerce de d\u00e9tail AFP",
  "Assistant en audiovision avec brevet f\u00e9d\u00e9ral",
  "Assistant en boucherie et charcuterie AFP",
  "assistant en droit dipl\u00f4m\u00e9 ES",
  "Assistant en maintenance d\'automobiles AFP",
  "Assistant en m\u00e9decine v\u00e9t\u00e9rinaire CFC",
  "Assistant en m\u00e9dias imprim\u00e9s AFP",
  "Assistant en pharmacie CFC",
  "Assistant en podologie CFC",
  "Assistant en podologie CFC",
  "Assistant en promotion de l\u2019activit\u00e9 physique et de la sant\u00e9 CFC",
  "Assistant en soins et sant\u00e9 communautaire CFC",
  "Assistant en tourisme avec brevet f\u00e9d\u00e9ral",
  "Assistant en traitement de surface AFP",
  "Assistant m\u00e9dical CFC",
  "Assistant socio-\u00e9ducatif CFC",
  "Assistant sp\u00e9cialis\u00e9 en soins de longue dur\u00e9e et accompagnement avec brevet f\u00e9d\u00e9ral",
  "Assistant vernisseur AFP",
  "Assistant-constructeur de fondations AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de fondations AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de routes AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de routes AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de sols industriels et de chapes AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de sols industriels et de chapes AFP (champ professionnel Construction de voies de communication)",
  "Assistant-constructeur de voies ferr\u00e9es AFP (champ professionnel Construction de voies de communication)",
  "Audioproth\u00e9siste avec brevet f\u00e9d\u00e9ral",
  "Automaticien CFC",
  "Aviculteur CFC (Champ professionnel de l\'agriculture)",
  "Bijoutier CFC",
  "Bijoutier, ma\u00eetre",
  "Bottier-orthop\u00e9diste",
  "Bottier-orthop\u00e9diste CFC",
  "Bottier-orthop\u00e9diste dipl\u00f4m\u00e9, ma\u00eetre",
  "Boucher-charcutier CFC",
  "Boucher-charcutier, ma\u00eetre",
  "Boulanger-p\u00e2tissier-confiseur AFP",
  "Boulanger-p\u00e2tissier-confiseur CFC",
  "Cabin Crew Member avec brevet f\u00e9d\u00e9ral",
  "Cadre diplom\u00e9 des organisations de secours",
  "Calorifugeur-t\u00f4lier",
  "Calorifugeur-t\u00f4lier CFC",
  "Calorifugeur-t\u00f4lier, ma\u00eetre",
  "Carreleur CFC",
  "Carreleur, ma\u00eetre",
  "Carrossier, ma\u00eetre",
  "Carrossier-peintre CFC",
  "Carrossier-t\u00f4lier CFC",
  "Caviste CFC (Champ professionnel de l\'agriculture)",
  "C\u00e9ramiste",
  "C\u00e9ramiste CFC",
  "C\u00e9ramiste industriel CFC",
  "Charpentier",
  "Charpentier CFC",
  "Charpentier, ma\u00eetre",
  "Charron",
  "Charron, ma\u00eetre",
  "Chef boulanger-p\u00e2tissier-confiseur avec brevet f\u00e9d\u00e9ral",
  "Chef carreleur avec brevet f\u00e9d\u00e9ral",
  "Chef confiseur-p\u00e2tissier-glacier avec brevet f\u00e9d\u00e9ral",
  "Chef cuisinier avec brevet f\u00e9d\u00e9ral",
  "Chef d\'atelier en machines agricoles avec brevet f\u00e9d\u00e9ral",
  "Chef d\'atelier en machines de chantier avec brevet f\u00e9d\u00e9ral",
  "Chef d\'atelier d\'appareils \u00e0 moteur avec brevet f\u00e9d\u00e9ral",
  "Chef d\'atelier et de montage en construction m\u00e9tallique avec brevet f\u00e9d\u00e9ral",
  "Chef d\'entreprise de l\'h\u00f4tellerie et de la restauration diplom\u00e9",
  "Chef d\'entreprise diplom\u00e9e en boulangerie-p\u00e2tisserie-confiserie",
  "Chef d\'\u00e9tablissement de l\'h\u00f4tellerie et de la restauration avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exp\u00e9dition dipl\u00f4m\u00e9",
  "Chef d\'exploitation agricole avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation arboricole avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation avicole avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation caviste avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation \u00e9conomie carn\u00e9e avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation mara\u00eech\u00e8re avec brevet f\u00e9d\u00e9ral",
  "Chef d\'exploitation viticole avec brevet f\u00e9d\u00e9ral",
  "Chef de commerce international dipl\u00f4m\u00e9",
  "Chef de cuisine avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Chef de la restauration avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Chef de la restauration collective avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Chef de logistique dipl\u00f4m\u00e9",
  "Chef de marketing dipl\u00f4m\u00e9",
  "Chef de production en menuiserie",
  "Chef de production technique des mati\u00e8res synth\u00e9tiques dipl\u00f4m\u00e9",
  "Chef de projet en menuiserie",
  "Chef de projet en montage solaire avec brevet f\u00e9d\u00e9ral",
  "Chef de projet en technique du b\u00e2timent avec brevet f\u00e9d\u00e9ral",
  "Chef de projet et chef d\'atelier en construction de tableaux \u00e9lectriques avec brevet f\u00e9d\u00e9ral",
  "Chef de projet syst\u00e8mes de s\u00e9curit\u00e9 avec brevet f\u00e9d\u00e9ral",
  "Chef de projet verre avec brevet f\u00e9d\u00e9ral",
  "Chef de projets constructeur sur m\u00e9tal avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Chef de r\u00e9ception avec brevet f\u00e9d\u00e9ral",
  "Chef de service apr\u00e8s-vente dipl\u00f4m\u00e9",
  "Chef de vente dipl\u00f4m\u00e9",
  "Chef du secteur h\u00f4telier-intendance avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Chef monteur-frigoriste avec brevet f\u00e9d\u00e9ral",
  "Chef poseur de rev\u00eatements de sols avec brevet f\u00e9d\u00e9ral",
  "Chef-monteur en \u00e9chafaudage avec brevet f\u00e9d\u00e9ral",
  "Cidrier avec dipl\u00f4me de ma\u00eetrise",
  "Coiffeur AFP",
  "Coiffeur avec brevet f\u00e9d\u00e9ral",
  "Coiffeur avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Coiffeur CFC",
  "Coiffeur CFC",
  "Coloriste avec brevet f\u00e9d\u00e9ral",
  "Concepteur artisan avec brevet f\u00e9d\u00e9ral",
  "Concepteur en multim\u00e9dia",
  "Concierge avec brevet f\u00e9d\u00e9ral",
  "Conducteur d\'engins forestier avec brevet f\u00e9d\u00e9ral",
  "Conducteur de camion",
  "Conducteur de v\u00e9hicules l\u00e9gers AFP",
  "Conducteur de v\u00e9hicules lourds CFC",
  "Confectionneur AFP",
  "Conseil en brevets",
  "Conseiller dans le domaine psychosocial avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Conseiller de service \u00e0 la client\u00e8le dans la branche automobile avec brevet f\u00e9d\u00e9ral",
  "Conseiller de vente automobile avec brevet f\u00e9d\u00e9ral",
  "Conseiller de vente en horlogerie avec brevet f\u00e9d\u00e9ral",
  "Conseiller en affections respiratoires et tuberculose avec brevet f\u00e9d\u00e9ral",
  "Conseiller en am\u00e9nagement int\u00e9rieur avec brevet f\u00e9d\u00e9ral",
  "Conseiller en couleurs et en styles de mode avec brevet f\u00e9d\u00e9ral",
  "Conseiller en \u00e9nergie et en efficacit\u00e9 \u00e9nerg\u00e9tique avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Conseiller en environnement avec brevet federal",
  "Conseiller en milieu rural dipl\u00f4m\u00e9",
  "Conseiller en organisation avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Conseiller en relations publiques avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Conseiller en rev\u00eatements de sols avec brevet f\u00e9d\u00e9ral",
  "Conseiller en s\u00e9curit\u00e9 \u00e9lectrique avec brevet f\u00e9d\u00e9ral",
  "Conseiller \u00e9nerg\u00e9tique du b\u00e2timent avec brevet f\u00e9d\u00e9ral",
  "Conseiller financier avec brevet f\u00e9d\u00e9ral",
  "Constructeur de ski (LU)",
  "Constructeur d\'appareils industriels",
  "Constructeur d\'\u00e9l\u00e9ments en b\u00e9ton pr\u00e9fabriqu\u00e9s CFC",
  "Constructeur d\'installation de ventilation CFC",
  "Constructeur de bateaux",
  "Constructeur de bateaux CFC",
  "Constructeur de fondations CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de fondations CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de routes CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de routes CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de sols industriels et de chapes CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de sols industriels et de chapes CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de voies ferr\u00e9es CFC (champ professionnel Construction de voies de communication)",
  "Constructeur de voies ferr\u00e9es CFC (champ professionnel Construction de voies de communication)",
  "Constructeur d\u2019appareils industriels CFC",
  "Constructeur m\u00e9tallique CFC",
  "Constructeur m\u00e9tallique, ma\u00eetre",
  "Constructeur naval, ma\u00eetre",
  "Contact Center Supervisor avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre charpentier avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre de construction de fondations avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre de construction de routes avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre de construction de sols industriels et de chapes avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre de sciage d\'\u00e9difice avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre de voies ferr\u00e9es avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre en chauffage avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre en entretien de routes avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre en ferblanterie avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre en ventilation avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre forestier avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre jardinier avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre ma\u00e7on avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre paveur avec brevet f\u00e9d\u00e9ral (champ professionnel Construction de voies de communication)",
  "Contrema\u00eetre peintre avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre pl\u00e2trier-constructeur \u00e0 sec avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre Polybat avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre ramoneur avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre sanitaire avec brevet f\u00e9d\u00e9ral",
  "Contrema\u00eetre vitrier avec brevet f\u00e9d\u00e9ral",
  "Contr\u00f4leur de combustion avec brevet f\u00e9d\u00e9ral",
  "contr\u00f4leur de la circulation a\u00e9rienne diplom\u00e9 ES",
  "Contr\u00f4leur de mat\u00e9riaux de construction avec brevet f\u00e9d\u00e9ral",
  "Coordinateur d\'atelier automobile avec brevet f\u00e9d\u00e9ral",
  "Coordinateur en m\u00e9decine ambulatoire orientation clinique avec brevet f\u00e9d\u00e9ral",
  "Coordinateur en m\u00e9decine ambulatoire orientation gestion avec brevet f\u00e9d\u00e9ral",
  "Cordonnier CFC",
  "Cordonnier, ma\u00eetre",
  "Correcteur avec brevet f\u00e9d\u00e9ral (BF)",
  "Courtepointier CFC",
  "Courtepointier dipl\u00f4m\u00e9",
  "Courtier en immeubles avec brevet f\u00e9d\u00e9ral",
  "Coutelier",
  "Coutelier CFC",
  "Coutelier, ma\u00eetre",
  "Couturier avec brevet f\u00e9d\u00e9ral",
  "Couturier dipl\u00f4m\u00e9",
  "couturier d\u2019int\u00e9rieur AFP",
  "Cr\u00e9ateur de textiles int\u00e9rieurs avec brevet f\u00e9d\u00e9ral",
  "Cr\u00e9ateur de tissu CFC",
  "Cr\u00e9ateur de v\u00eatements",
  "Cr\u00e9ateur de v\u00eatements CFC",
  "Croupier avec brevet f\u00e9d\u00e9ral",
  "Cuisinier CFC",
  "Cuisinier en di\u00e9t\u00e9tique CFC",
  "Danseur interpr\u00e8te CFC",
  "D\u00e9clarant de douane avec brevet f\u00e9d\u00e9ral",
  "D\u00e9corateur d\'int\u00e9rieur avec brevet f\u00e9d\u00e9ral",
  "D\u00e9corateur d\'int\u00e9rieurs",
  "D\u00e9corateur d\'int\u00e9rieurs dipl\u00f4m\u00e9",
  "Dermapigmentologue avec brevet f\u00e9d\u00e9ral",
  "designer dipl\u00f4m\u00e9 ES en arts visuels",
  "designer dipl\u00f4m\u00e9 ES en communication visuelle",
  "designer dipl\u00f4m\u00e9 ES en design de produit",
  "Designer graphique diplom\u00e9",
  "Dessinateur CFC (champ professionnel planification du territoireet de la construction)",
  "Dessinateur en construction microtechnique CFC",
  "Dessinateur-constructeur en g\u00e9nie civil dipl\u00f4m\u00e9",
  "Dessinateur-constructeur en microtechnique",
  "Dessinateur-constructeur industriel CFC",
  "Dessinateur-constructeur sur m\u00e9tal CFC",
  "D\u00e9veloppeur immobilier avec brevet f\u00e9d\u00e9ral",
  "Diagnosticien d\'automobiles avec brevet f\u00e9d\u00e9ral",
  "dipl. Abteilungsleiter Gesundheit NDS HF",
  "dipl. Baubetriebsmanager NDS HF",
  "dipl. Bauprojekt- und Immobilienmanager NDS HF",
  "dipl. Berater in Ver\u00e4nderungsprozessen NDS HF",
  "dipl. Betriebswirtschafter NDS HF",
  "dipl. Business Analyst NDS HF",
  "dipl. Business Banker NDS HF",
  "dipl. Business Coach NDS HF",
  "dipl. Business Engineer NDS HF",
  "dipl. Controller NDS HF",
  "dipl. Energieberater NDS HF",
  "dipl. Erlebnisp\u00e4dagoge NDS HF",
  "dipl. Experte in Leadership und Change Management NDS HF",
  "dipl. Experte in strategischem Management NDS HF",
  "dipl. Finanzchef NDS HF",
  "dipl. Finanzexperte NDS HF",
  "dipl. Gesch\u00e4ftsf\u00fchrer NDS HF",
  "dipl. Hotelmanager NDS HF",
  "dipl. HR-Experte NDS HF",
  "dipl. Human Resource Manager NDS HF",
  "dipl. in Leadership und Management NDS HF",
  "dipl. in Unternehmens- und Mitarbeiterf\u00fchrung NDS HF",
  "dipl. IT-Service-Manager NDS HF",
  "dipl. Kommunikationstrainer NDS HF",
  "dipl. Leiter Finanzen und Dienste NDS HF",
  "dipl. Leiter interne Kommunikation und Management Support NDS",
  "dipl. Logistikleiter NDS HF",
  "dipl. logotherapeutischer Berater NDS HF",
  "dipl. Marketing- und Verkaufsleiter NDS HF",
  "dipl. Marketing- und Verkaufsmanager NDS HF",
  "dipl. Marketingmanager NDS HF",
  "dipl. Network Engineer NDS HF",
  "dipl. Online-Marketingmanager NDS HF",
  "dipl. Personalleiter NDS HF",
  "dipl. Produktmanager Textil NDS HF",
  "dipl. Projekt- und Prozessmanager NDS HF",
  "dipl. Projektleiter NDS HF",
  "dipl. Projektmanager NDS HF",
  "dipl. Qualit\u00e4ts- und Prozessmanager NDS HF",
  "dipl. Qualit\u00e4tsmanager NDS HF",
  "dipl. Umfassende Leadership NDS HF",
  "dipl. Umfassendes Controlling NDS HF",
  "dipl. Unternehmensf\u00fchrer NDS HF",
  "dipl. Unternehmensleiter NDS HF",
  "Diplom in Energiemanagement NDS HF",
  "Diplom in Unternehmensf\u00fchrung NDS HF",
  "Directeur d\'\u00e9cole d\'une discipline sportive avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Directeur d\'institution de l\'enfance dipl\u00f4m\u00e9 EPD ES",
  "Directeur d\'institution sociale et m\u00e9dico-sociale diolom\u00e9",
  "Directeur de studio de gymnastique avec brevet f\u00e9d\u00e9ral",
  "Directeur des travaux du b\u00e2timent dipl\u00f4m\u00e9",
  "Directeur des travaux du g\u00e9nie civil dipl\u00f4m\u00e9",
  "Dirigeant d\'entreprise avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Dirigeant de maintenance dipl\u00f4m\u00e9",
  "Dirigeant diplom\u00e9 en facility management",
  "Doreur-Encadreur CFC",
  "Droguiste CFC",
  "Eb\u00e9niste CFC",
  "Eb\u00e9niste, ma\u00eetre",
  "Ecobiologiste de la construction avec brevet f\u00e9d\u00e9ral",
  "Ecobiologiste de la construction dipl\u00f4m\u00e9",
  "\u00e9conomiste bancaire diplom\u00e9 ES",
  "\u00e9conomiste d\'assurance dipl\u00f4m\u00e9 ES",
  "\u00e9conomiste d\'entreprise dipl\u00f4m\u00e9 ES",
  "Economiste d\'entreprise PME avec dipl\u00f4me f\u00e9d\u00e9ral",
  "\u00e9ducateur de l\'enfance dipl\u00f4m\u00e9. ES",
  "\u00e9ducateur social diplom\u00e9 ES",
  "\u00e9ducateur social dipl\u00f4m\u00e9 ES",
  "Electricien chef de projet avec brevet f\u00e9d\u00e9ral",
  "Electricien de montage CFC",
  "Electricien de montage CFC",
  "Electricien de r\u00e9seau",
  "Electricien de r\u00e9seau CFC",
  "Electricien de r\u00e9seau, ma\u00eetre, diplom\u00e9",
  "Electronicien CFC",
  "Electronicien en multim\u00e9dia",
  "Electronicien en multim\u00e9dia avec brevet f\u00e9d\u00e9ral",
  "Electronicien en multim\u00e9dia CFC",
  "Electroplaste avec brevet f\u00e9d\u00e9ral",
  "Electroplaste CFC",
  "Electroplaste dipl\u00f4m\u00e9",
  "Employ\u00e9 de commerce",
  "Employ\u00e9 de commerce CFC",
  "Employ\u00e9 de remont\u00e9es m\u00e9caniques AFP",
  "Employ\u00e9 d\u2019exploitation AFP",
  "Employ\u00e9 en cuisine AFP",
  "Employ\u00e9 en h\u00f4tellerie AFP",
  "Employ\u00e9 en industrie laiti\u00e8re AFP",
  "Employ\u00e9 en intendance AFP",
  "Employ\u00e9 en intendance AFP",
  "Employ\u00e9 en restauration AFP",
  "Enqu\u00eateur de douane avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Entra\u00eeneur de sport de performance avec brevet f\u00e9d\u00e9ral",
  "Entra\u00eeneur dipl\u00f4m\u00e9 de sport d\'Elite",
  "Entrepreneur de pompes fun\u00e8bres avec brevet f\u00e9d\u00e9ral",
  "Entrepreneur-construction dipl\u00f4m\u00e9",
  "Esth\u00e9ticien avec brevet f\u00e9d\u00e9ral",
  "Esth\u00e9ticien CFC",
  "Esth\u00e9ticien dipl\u00f4m\u00e9",
  "Expert dipl\u00f4m\u00e9 en assurance-maladie",
  "Expert dipl\u00f4m\u00e9 en assurances de pension",
  "Expert dipl\u00f4m\u00e9 en assurances sociales",
  "Expert dipl\u00f4m\u00e9 en conduite organisationelle",
  "Expert dipl\u00f4m\u00e9 en finance et en controlling",
  "Expert dipl\u00f4m\u00e9 en finance et investissements",
  "Expert dipl\u00f4m\u00e9 en tourisme",
  "Expert domaine op\u00e9ratoire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert du domaine des privations de libert\u00e9 avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert du domaine \u00e9guin avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en analyses biom\u00e9dicales et gestion de laboratoire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en cytodiagnostic avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en douane diplom\u00e9 ES",
  "Expert en estimations immobili\u00e8res avec brevet f\u00e9d\u00e9ral",
  "Expert en finance de PME avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en gestion hospitali\u00e8re avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en management de l\'organisation avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en op\u00e9rations des march\u00e9s financiers avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en pr\u00e9vention des infections associ\u00e9es aux soins avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert en production avec brevet f\u00e9d\u00e9ral",
  "Expert en soins d\u2019anesth\u00e9sie dipl\u00f4m\u00e9 EPD ES",
  "Expert en soins d\u2019urgence dipl\u00f4m\u00e9 EPD ES",
  "Expert en soins intensifs dipl\u00f4m\u00e9 EPD ES",
  "Expert fiduciaire dipl\u00f4m\u00e9",
  "Expert fiscal dipl\u00f4m\u00e9",
  "Expert protection incendie avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Expert-comptable dipl\u00f4m\u00e9",
  "Expert-soudeur avec brevet f\u00e9d\u00e9ral",
  "Exploitant de station d\'\u00e9puration avec brevet f\u00e9d\u00e9ral",
  "Facteur d\'instruments de musique CFC",
  "Fashion sp\u00e9cialiste avec brevet f\u00e9d\u00e9ral",
  "Fashiondesigner avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Ferblantier CFC",
  "Fleuriste AFP",
  "Fleuriste avec brevet f\u00e9d\u00e9ral",
  "Fleuriste CFC",
  "Fleuriste, ma\u00eetre",
  "Flexographe CFC",
  "Fontainier avec brevet f\u00e9d\u00e9ral",
  "forestier dipl\u00f4m\u00e9 ES",
  "Forestier-b\u00fbcheron CFC",
  "Forgeron, ma\u00eetre",
  "Formateur avec brevet f\u00e9d\u00e9ral",
  "Fourreur, ma\u00eetre",
  "Gainier",
  "Garde-faune avec brevet f\u00e9d\u00e9ral",
  "Garde-fronti\u00e8re avec brevet f\u00e9d\u00e9ral",
  "Garde-fronti\u00e8re avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Garde-p\u00eache avec brevet f\u00e9d\u00e9ral",
  "Gardien d\'immeuble dipl\u00f4m\u00e9",
  "Gardien de cheval AFP",
  "Gardien de chevaux AFP",
  "Gardien d\u2019animaux CFC",
  "Garnisseur de meubles CFC",
  "Garnisseur de meubles industriels avec brevet f\u00e9d\u00e9ral",
  "Garnisseur de meubles industriels, ma\u00eetre",
  "Garnisseur de meubles sp\u00e9cialis\u00e9 avec brevet f\u00e9d\u00e9ral",
  "Garnisseur en carrosserie",
  "G\u00e9omaticien CFC",
  "G\u00e9rant d\'immeubles avec brevet f\u00e9d\u00e9ral",
  "G\u00e9rant de caisse de pension dipl\u00f4m\u00e9",
  "Gestionnaire d\'entreprise dipl\u00f4m\u00e9 de la branche automobile",
  "Gestionnaire d\'entreprise dipl\u00f4m\u00e9 secteur automobile",
  "Gestionnaire du commerce de d\u00e9tail CFC",
  "Gestionnaire en intendance CFC",
  "Gestionnaire en intendance CFC",
  "Gestionnaire en tourisme de sant\u00e9 et d\'activit\u00e9 avec dipl\u00f4me f\u00e9d\u00e9ral",
  "gestionnaire en tourisme dipl\u00f4m\u00e9 ES",
  "Gouvernant de maison avec brevet f\u00e9d\u00e9ral",
  "Graphiste CFC",
  "Graveur",
  "Graveur CFC",
  "Guide de montagne avec brevet f\u00e9d\u00e9ral",
  "Guide touristique avec brevet f\u00e9d\u00e9ral",
  "Horloger CFC",
  "Horloger dans le domaine professionnel de l\'industrie",
  "Horloger dans le domaine professionnel du rhabillage",
  "Horloger de production CFC",
  "Horloger praticien",
  "Horloger, ma\u00eetre",
  "Horticulteur",
  "Horticulteur AFP",
  "Horticulteur CFC",
  "H\u00f4telier-Restaurateur dipl\u00f4m\u00e9 ES",
  "hygi\u00e9niste dentaire dipl\u00f4m\u00e9 ES",
  "ICT-Manager diplom\u00e9",
  "infirmier dipl\u00f4m\u00e9 ES",
  "infirmier dipl\u00f4m\u00e9 ES",
  "Informaticien CFC",
  "Informaticien CFC",
  "Informaticien de gestion avec brevet f\u00e9d\u00e9ral",
  "informaticien de gestion dipl\u00f4m\u00e9 ES",
  "Informaticien en d\u00e9veloppement d\'application TIC avec brevet f\u00e9d\u00e9ral",
  "Informaticien en technique des syst\u00e8mes et r\u00e9seaux TIC avec brevet f\u00e9d\u00e9ral",
  "Installateur en chauffage CFC",
  "Installateur sanitaire CFC",
  "Installateur-\u00e9lectricien CFC",
  "Installateur-\u00e9lectricien CFC",
  "Installateur-\u00e9lectricien dipl\u00f4m\u00e9",
  "Instructeur de chiens guides d\'aveugles avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Instructeur de fitness avec brevet f\u00e9d\u00e9ral",
  "intendant du secteur h\u00f4telier d\'\u00e9tablissement dipl\u00f4m\u00e9 ES",
  "Interactive Media Designer CFC",
  "Key account manager dipl\u00f4m\u00e9",
  "Laborantin CFC",
  "Laborantin en physique",
  "Laborantin en physique CFC",
  "Laboriste",
  "Libraire avec brevet f\u00e9d\u00e9ral",
  "Libraire CFC",
  "Logisticien AFP",
  "Logisticien AFP",
  "Logisticien avec brevet f\u00e9d\u00e9ral",
  "Logisticien avec brevet f\u00e9d\u00e9ral",
  "Logisticien avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Logisticien CFC",
  "Logisticien CFC",
  "Luthier",
  "Luthier, ma\u00eetre",
  "Ma\u00e7on CFC",
  "Ma\u00eetre agriculteur",
  "Ma\u00eetre arboriculteur",
  "Ma\u00eetre aviculteur",
  "Ma\u00eetre caviste",
  "Ma\u00eetre chauffagiste avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Ma\u00eetre dans l\'industrie",
  "Ma\u00eetre du cuir et du textile",
  "Ma\u00eetre ferblantier avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Ma\u00eetre jardinier",
  "Ma\u00eetre mara\u00eecher",
  "Ma\u00eetre peintre",
  "Ma\u00eetre Polybat",
  "Ma\u00eetre poseur de rev\u00eatements de sols",
  "Ma\u00eetre Ramoneur",
  "Ma\u00eetre sanitaire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Ma\u00eetre scultpeur sur bois",
  "ma\u00eetre socioprofessionnel dipl\u00f4m\u00e9 ES",
  "Ma\u00eetre tableaux \u00e9lectriques et automation",
  "Ma\u00eetre textile avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Ma\u00eetre viticulteur",
  "Ma\u00eetre vitrier",
  "Manager de m\u00e9dias dipl\u00f4m\u00e9",
  "Manager de remont\u00e9es m\u00e9canique avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Manager en commerce de d\u00e9tail avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Manager en publication avec dipl\u00f4me f\u00e9d\u00e9ral (DF)",
  "Manager en syst\u00e8mes de transports publics dipl\u00f4m\u00e9",
  "Maquettiste d\'architecture",
  "Maquilleur professionnel avec brevet f\u00e9d\u00e9ral",
  "Mara\u00eecher CFC (Champ professionnel de l\'agriculture)",
  "Marbrier CFC (Champ professionnel travail de la pierre)",
  "Marbrier du b\u00e2timent CFC (Champ professionnel travail de la pierre)",
  "Marbrier, ma\u00eetre",
  "Mar\u00e9chal-ferrant CFC",
  "Mar\u00e9chal-forgeron, ma\u00eetre",
  "marketing manager dipl\u00f4m\u00e9 ES",
  "Masseur m\u00e9dical avec brevet f\u00e9d\u00e9ral",
  "Matelot de la navigation int\u00e9rieure CFC",
  "M\u00e9canicien d\'appareils \u00e0 moteur CFC",
  "M\u00e9canicien d\'appareils \u00e0 moteur, ma\u00eetre",
  "M\u00e9canicien de production CFC",
  "M\u00e9canicien deux-roues",
  "M\u00e9canicien en bicyclettes et motocyclettes, ma\u00eetre",
  "M\u00e9canicien en bicyclettes, ma\u00eetre",
  "M\u00e9canicien en cycles CFC",
  "M\u00e9canicien en machines agricoles CFC",
  "M\u00e9canicien en machines agricoles, ma\u00eetre",
  "M\u00e9canicien en machines de chantier CFC",
  "M\u00e9canicien en machines de chantier, ma\u00eetre",
  "M\u00e9canicien en maintenance d\'automobiles CFC",
  "M\u00e9canicien en motocycles",
  "M\u00e9canicien en motocycles CFC",
  "M\u00e9canicien en motocycles de petite cylindr\u00e9e et cycles CFC",
  "M\u00e9catronicien d\'automobiles CFC",
  "M\u00e9catronicien de remont\u00e9es m\u00e9caniques CFC",
  "M\u00e9diamaticien",
  "M\u00e9diamaticien avec brevet f\u00e9d\u00e9ral",
  "M\u00e9diamaticien CFC",
  "Mentor d\'entreprise avec brevet f\u00e9d\u00e9ral",
  "Menuisier, ma\u00eetre",
  "Menuisier",
  "Meunier",
  "Meunier CFC",
  "Microm\u00e9canicien",
  "Microm\u00e9canicien CFC",
  "Modeleur-c\u00e9ramiste",
  "Moniteur de conduite avec brevet f\u00e9d\u00e9ral",
  "Monteur automaticien CFC",
  "Monteur de faux plafonds avec brevet f\u00e9d\u00e9ral",
  "Monteur de r\u00e9seaux eau et gaz avec brevet f\u00e9d\u00e9ral",
  "Monteur frigoriste CFC",
  "Monteur-frigoriste",
  "Mouleur CFC",
  "Mouleur de fonderie",
  "Mouleur de fonderie CFC",
  "Naturopathe avec dipl\u00f4me f\u00e9d\u00e9ral",
  "N\u00e9gociant de vins dipl\u00f4m\u00e9",
  "Nettoyeur chimique dipl\u00f4m\u00e9",
  "Nettoyeur de b\u00e2timents diplom\u00e9",
  "Nettoyeur de textiles CFC",
  "Officier de l\'\u00e9tat civil avec brevet f\u00e9d\u00e9ral",
  "Op\u00e9rateur d\'installations de centrale nucl\u00e9aire avec brevet f\u00e9d\u00e9ral",
  "Op\u00e9rateur de machines automatis\u00e9es CFC",
  "Op\u00e9rateur de m\u00e9dias imprim\u00e9s CFC",
  "Op\u00e9rateur de sciage d\u2019\u00e9difice CFC",
  "Op\u00e9rateur en horlogerie AFP",
  "Op\u00e9rateur en horlogerie AFP",
  "Opticien CFC",
  "Opticien en instruments",
  "Opticien en instruments de pr\u00e9cision CFC",
  "Orf\u00e8vre en argenterie, ma\u00eetre",
  "Orthop\u00e9diste CFC",
  "Orthop\u00e9diste dipl\u00f4m\u00e9",
  "orthoptiste dipl\u00f4m\u00e9 ES",
  "Packaging Manager avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Papetier",
  "Papetier CFC",
  "P\u00e2tissier-confiseur dipl\u00f4m\u00e9",
  "Paveur CFC (champ professionnel Construction de voies de communication)",
  "Paveur CFC (champ professionnel Construction de voies de communication)",
  "Paveur, ma\u00eetre",
  "P\u00eacheur professionnel avec brevet f\u00e9d\u00e9ral",
  "Peintre CFC",
  "Peintre en automobiles avec brevet f\u00e9d\u00e9ral",
  "Peintre en b\u00e2timents",
  "Peintre en d\u00e9cors de th\u00e9\u00e2tre",
  "Peintre en d\u00e9cors de th\u00e9\u00e2tre CFC",
  "Peintre verrier CFC",
  "Photodesigner diplom\u00e9",
  "Photographe",
  "Photographe CFC",
  "Photographe de laboratoire",
  "Physioth\u00e9rapeut pour animaux avec dipl\u00f4me f\u00e9d\u00e9ral",
  "pilote dipl\u00f4m\u00e9 ES",
  "Planificateur \u00e9clairagiste avec brevet f\u00e9d\u00e9ral",
  "Planificateur en communication avec brevet f\u00e9d\u00e9ral",
  "Planificateur-\u00e9lectricien CFC",
  "Planificateur-\u00e9lectricien CFC",
  "Planificateur-\u00e9lectricien dipl\u00f4m\u00e9",
  "Pl\u00e2trier",
  "Pl\u00e2trier constructeur \u00e0 sec CFC",
  "Pl\u00e2trier, ma\u00eetre",
  "Pl\u00e2trier-peintre",
  "podologue dipl\u00f4m\u00e9 ES",
  "Po\u00ealier-fumiste CFC",
  "Po\u00ealier-fumiste, ma\u00eetre",
  "Po\u00ealier-fumiste, ma\u00eetre",
  "Policier avec brevet f\u00e9d\u00e9ral",
  "Policier avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Polisseur AFP",
  "Polyb\u00e2tisseur CFC",
  "Polydesigner 3D CFC",
  "Polygraphe CFC",
  "Polygraphe CFC",
  "Polym\u00e9canicien CFC",
  "Poseur de pierres AFP (champ professionnel Construction de voies de communication)",
  "Poseur de pierres AFP (champ professionnel Construction de voies de communication)",
  "Poseur de rev\u00eatements de sols",
  "Poseur de sol \u2013 parquet CFC",
  "Praticien des mati\u00e8res synth\u00e9tiques AFP",
  "Praticien en denr\u00e9es alimentaires AFP",
  "Praticien en m\u00e9canique AFP",
  "Praticien en pneumatiques AFP",
  "Praticien forestier AFP",
  "Praticien sur bois AFP",
  "Pr\u00e9parateur Humains avec brevet f\u00e9d\u00e9ral",
  "Professeur d\'escalade avec brevet f\u00e9d\u00e9ral",
  "Professeur de cano\u00eb-kayak avec brevet f\u00e9d\u00e9ral",
  "Professeur de danse de couple avec brevet f\u00e9d\u00e9ral",
  "Professeur de golf avec brevet f\u00e9d\u00e9ral",
  "Professeur de ju-jitsu avec brevet f\u00e9d\u00e9ral",
  "Professeur de judo avec brevet f\u00e9d\u00e9ral",
  "Professeur de karat\u00e9 avec brevet f\u00e9d\u00e9ral",
  "Professeur de patinage avec brevet f\u00e9d\u00e9ral",
  "Professeur de planche \u00e0 voile avec brevet f\u00e9d\u00e9ral",
  "Professeur de sport de neige avec brevet f\u00e9d\u00e9ral",
  "Professeur de sports aquatiques avec brevet f\u00e9d\u00e9ral",
  "Professeur de tennis avec brevet f\u00e9d\u00e9ral",
  "Professeur de voile avec brevet f\u00e9d\u00e9ral",
  "Professeur en navigation de bateau moteur avec brevet f\u00e9d\u00e9ral",
  "Professionnel du cheval CFC",
  "Professionnel du cheval CFC",
  "Projeteur constructeur sur m\u00e9tal avec brevet f\u00e9d\u00e9ral",
  "Projeteur en sanitaire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Projeteur en technique du b\u00e2timent",
  "Projeteur en technique du b\u00e2timent chauffage CFC (champ professionnel Planification en technique du b\u00e2timent)",
  "Projeteur en technique du b\u00e2timent sanitaire CFC (champ professionnel Planification en technique du b\u00e2timent)",
  "Projeteur en technique du b\u00e2timent ventilation CFC (champ professionnel Planification en technique du b\u00e2timent)",
  "Projeteur frigoriste CFC",
  "Ramoneur CFC",
  "R\u00e9alisateur publicaire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "R\u00e9alisateur publicitaire CFC",
  "R\u00e9alisateur publicitaire CFC",
  "Recycleur CFC",
  "R\u00e9dacteur publicitaire avec brevet f\u00e9d\u00e9ral",
  "R\u00e9dacteur technique avec brevet f\u00e9d\u00e9ral",
  "R\u00e9parateur de chaussures AFP",
  "Repousseur-emboutisseur",
  "Responsable Achats avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Responsable d\'\u00e9quipe dans des institutions sociales et m\u00e9dico-sociales avec brevet f\u00e9d\u00e9ral",
  "Responsable de formation avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Responsable de la communication diplom\u00e9",
  "Responsable de la restauration avec brevet f\u00e9d\u00e9ral",
  "Responsable de m\u00e9nage agricole avec brevet f\u00e9d\u00e9ral",
  "Responsable de m\u00e9nage agricole diplom\u00e9",
  "Responsable dipl\u00f4m\u00e9 en documentation technique",
  "Responsable du secteur h\u00f4telier - intendance avec brevet f\u00e9d\u00e9ral",
  "Responsable en transport et logistique dipl\u00f4m\u00e9",
  "Responsable dipl\u00f4m\u00e9 en ressources humaines",
  "Restaurateur de livres dipl\u00f4m\u00e9",
  "Sapeur-pompier professionnel avec brevet f\u00e9d\u00e9ral",
  "Scieur de l\'industrie du bois CFC",
  "Screen Communicator avec brevet f\u00e9d\u00e9ral",
  "Sculpteur sur bois CFC",
  "Sculpteur sur pierre CFC (Champ professionnel travail de la pierre)",
  "Sculpteur sur pierre, ma\u00eetre",
  "Secouriste routier avec brevet f\u00e9deral",
  "Sellier",
  "S\u00e9rigraphe, ma\u00eetre",
  "Serrurier sur v\u00e9hicules avec brevet f\u00e9d\u00e9ral",
  "Serrurier sur v\u00e9hicules CFC",
  "Sertisseur en joaillerie, ma\u00eetre",
  "Sommelier avec brevet f\u00e9d\u00e9ral",
  "Specialista in soluzioni mobile aziendali dipl. SPD SSS",
  "Sp\u00e9cialiste assainissement d\'ouvrage avec brevet federal",
  "Sp\u00e9cialiste c\u00e2ble-crue avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste d\'achat",
  "Sp\u00e9cialiste de commerce international avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de douane avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la conduite d\'\u00e9quipe avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la gestion et du d\u00e9veloppement des organisations syndicales avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la migration avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la nature et de l\'environnement avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la pr\u00e9voyance en faveur du personnel avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de la s\u00e9curit\u00e9 dans les institutions de sant\u00e9 et du social avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de logistique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de m\u00e9dias avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de r\u00e9seau avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de traitement des mati\u00e8res premi\u00e8res avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste de vente avec brevet federal",
  "Sp\u00e9cialiste des branches de la boulangerie-p\u00e2tisserie-confiserie avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste des installations de transport \u00e0 c\u00e2bles avec brevet f\u00e9d\u00e9ral",
  "sp\u00e9cialiste des services de la navigation a\u00e9rienne diplom\u00e9 ES",
  "Sp\u00e9cialiste du commerce de d\u00e9tail avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste du commerce fruits et l\u00e9gumes avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste du domain \u00e9quin avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste du service de pistes et de sauvetage avec brevet f\u00e9d\u00e9ral",
  "sp\u00e9cialiste en activation dipl\u00f4m\u00e9 ES",
  "Sp\u00e9cialiste en administration publique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en agriculture biodynamique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en assurance avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en assurance-maladie avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en assurances sociales avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en bois avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en codage m\u00e9dical avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en commerce de textile avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en diagnostic neurophysiologique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en finance et comptabilit\u00e9 avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en finition des m\u00e9dias imprim\u00e9s avec brevet f\u00e9d\u00e9ral (BF)",
  "Sp\u00e9cialiste en formation professionnelle avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en gestion de PME avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en gestion hospitali\u00e8re avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en h\u00f4tellerie CFC",
  "Sp\u00e9cialiste en impression et emballage avec brevet f\u00e9d\u00e9ral (BF)",
  "Sp\u00e9cialiste en interpr\u00e9tariat communautaire et m\u00e9diation interculturelle avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en marketing avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en mati\u00e8re de poursuite pour dettes et de la faillite avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en nettoyage de b\u00e2timents avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en organisation d\'entreprise avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en photographie avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en photographie CFC",
  "Sp\u00e9cialiste en photographie dipl\u00f4m\u00e9",
  "Sp\u00e9cialiste en pneumatiques avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en protection incendie avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en r\u00e9adaptation de personnes malvoyantes et aveugles avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en relations publiques avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en ressources humaines avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en restauration CFC",
  "Sp\u00e9cialiste en restauration de syst\u00e8me CFC",
  "Sp\u00e9cialiste en soin aux arbres avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en syst\u00e8mes thermiques avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en technologies de r\u00e9adaptation avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en thermique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en transports publics avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste en vernissage industriel avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste \u00e9tablissements de bains avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste minage avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste pharmaceutique avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste pour installations de traitement des d\u00e9chets avec brevet f\u00e9d\u00e9ral",
  "Sp\u00e9cialiste pour la s\u00e9curit\u00e9 des citernes avec brevet f\u00e9d\u00e9ral",
  "Styliste d\'ongles avec brevet f\u00e9d\u00e9ral",
  "Superviseur-Coach avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Supply Chain Manager diplom\u00e9",
  "Tailleur de pierre CFC (Champ professionnel travail de la pierre)",
  "Tailleur, ma\u00eetre",
  "Technicien ambulancier avec brevet f\u00e9d\u00e9ral",
  "Technicien de fouilles arch\u00e9ologiques avec brevet f\u00e9d\u00e9ral",
  "Technicien de laboratoire en sciences naturelles avec dipl\u00f4me f\u00e9d\u00e9ral",
  "technicien dipl\u00f4m\u00e9 ES agroalimentaire",
  "technicien dipl\u00f4m\u00e9 ES en informatique",
  "technicien dipl\u00f4m\u00e9 ES en microtechnique",
  "technicien dipl\u00f4m\u00e9 ES en t\u00e9l\u00e9communications",
  "technicien dipl\u00f4m\u00e9 ES g\u00e9nie \u00e9lectrique",
  "technicien dipl\u00f4m\u00e9 ES g\u00e9nie m\u00e9canique",
  "technicien dipl\u00f4m\u00e9 ES planification des travaux",
  "technicien diplom\u00e9 ES processus d\'entreprise",
  "technicien dipl\u00f4m\u00e9 ES syst\u00e8mes industriels",
  "technicien dipl\u00f4m\u00e9 ES technique des b\u00e2timents",
  "technicien dipl\u00f4m\u00e9 ES technique du bois",
  "Technicien du film avec brevet f\u00e9d\u00e9ral",
  "Technicien du son avec brevet f\u00e9d\u00e9ral",
  "Technicien du spectacle avec brevet f\u00e9d\u00e9ral",
  "technicien en analyses biom\u00e9dicales dipl\u00f4m\u00e9 ES",
  "Technicien en g\u00e9omatique avec brevet f\u00e9d\u00e9ral",
  "technicien en radiologie m\u00e9dicale dipl\u00f4m\u00e9 ES",
  "technicien en salle d\u2019op\u00e9ration dipl\u00f4m\u00e9 ES",
  "Technicien sur a\u00e9ronefs avec brevet f\u00e9d\u00e9ral",
  "Technicien vitivinicole dipl. ES",
  "Technicien-dentiste CFC",
  "Technicien-dentiste, ma\u00eetre",
  "Technisc\u00e9niste CFC",
  "Techno-polygraphe avec brevet f\u00e9d\u00e9ral (BF)",
  "Technologue de fonderie",
  "Technologue de fonderie CFC",
  "Technologue du lait CFC",
  "Technologue en assainissement CFC",
  "Technologue en chimie dipl\u00f4m\u00e9",
  "Technologue en denr\u00e9es alimentaires",
  "Technologue en denr\u00e9es alimentaires avec brevet f\u00e9d\u00e9ral",
  "Technologue en denr\u00e9es alimentaires avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Technologue en denr\u00e9es alimentaires CFC",
  "Technologue en emballage CFC",
  "Technologue en impression CFC",
  "Technologue en industrie laiti\u00e8re",
  "Technologue en industrie laiti\u00e8re avec brevet f\u00e9d\u00e9ral",
  "Technologue en industrie laiti\u00e8re diplom\u00e9",
  "Technologue en production chimique et pharmaceutique CFC",
  "Technologue en production chimique et pharmaceutique CFC",
  "Technologue en textile CFC",
  "T\u00e9l\u00e9maticien CFC",
  "T\u00e9l\u00e9maticien CFC",
  "T\u00e9l\u00e9maticien chef de projet avec brevet f\u00e9d\u00e9ral",
  "T\u00e9l\u00e9maticien dipl\u00f4m\u00e9",
  "Termineur en habillage horloger CFC",
  "Th\u00e9rapeute Compl\u00e9mentaire avec dipl\u00f4me f\u00e9d\u00e9ral",
  "Thermiste avec brevet f\u00e9d\u00e9ral",
  "T\u00f4lier en carrosserie avec brevet f\u00e9d\u00e9ral",
  "Tonnelier CFC",
  "Tourneur, ma\u00eetre",
  "Transitaire avec brevet f\u00e9d\u00e9ral",
  "Typographiste pour la communication visuelle avec brevet f\u00e9d\u00e9ral",
  "Vannier cr\u00e9ateur CFC",
  "V\u00e9rificateur des poids et mesures dipl\u00f4m\u00e9",
  "Vernisseur industriel CFC",
  "Vernisseur industriel CFC",
  "Viticulteur CFC (Champ professionnel de l\'agriculture)",
  "Vitrier",
  "Vitrier CFC",
  "Web Project Manager dipl\u00f4m\u00e9",
  "Zingueur avec brevet f\u00e9d\u00e9ral",
  "Zingueur dipl\u00f4m\u00e9"
)

#' Job provider for Zwitserland
#'
#' @inherit JobProvider description details return
#' @family fr
#' @family CH
#' @export
#' @examples
#' x <- JobProvider_fr_CH$new()
#' x$render()
JobProvider_fr_CH <- R6::R6Class(
  inherit = JobProvider,
  "JobProvider_fr_CH",
  private = list(
    locale_ = "fr_CH",
    formats = job_formats_fr_ch
  )
)
